services:
  - type: web
    name: mon-projet-symfony
    runtime: php
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: bdd-symfony
          property: connectionString
